language: ruby
branches:
  only:
    - master
    - develop
    - /^exercise-.*$/
    - /^feature\/.*$/
    - heroku/development
rvm:
  - 2.1.0
before_script:
  - bundle install
  - npm install
script:
  - bundle exec rake test
  - npm run-script test
  - bundle exec rake doc
  - npm run-script doc
after_script:
  - 
    if [ "${TRAVIS_BRANCH}" == "develop" ]; then
      git clone --quiet --single-branch -b gh-pages git://github.com/sh19910711/web-graph-visualizer.git tmp/gh-pages ;
      cp -r doc tmp/gh-pages/ ;
      cd tmp/gh-pages/ ;
      git config --global user.email "sh19910711@gmail.com" ;
      git config --global user.name "Hiroyuki Sano" ;
      git add doc &&
        git commit -m 'Update Document' &&
        git push --quiet https://${GITHUB_TOKEN}@github.com/sh19910711/web-graph-visualizer.git gh-pages ;
    fi
env:
  global:
    - secure: "SKgHTnxfWMgG2NeuMN9li+DKfL2dt+T6P6nIzhzbUdiF0QSo4Za6KGyJopRclrpc9lA+099SBx4viPTGL3s0x5nmVC1NWZUTNQt8v2vSjMf9mRVQYCz8LX8IEQURb+zWPgQWTdOa4YgAJOFa8/7qfC759daptHMOgcTcQDcquTM="
gemfile:
  - Gemfile
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a500e93876b7976aea71
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: heroku
  api_key:
    secure: "h4UaaDKAkZrI4B3zoBB/oBiHGlMHsi7EKv74QpCJku/yvULdKFtHnjY13P6C3giIPGfMNLx58eZkkmiOM0wzfSIVRujXq4JyxqYa0x0MhByFjt/cLBUOKgSRcOZK8jH9BRhDG8Tkn6vD8nqQzvZoF8c7b1X3pEZNiSv+9DYaesk="
  app:
    heroku/development: graph-visualizer-xkb

