language: ruby
branches:
  only:
    - master
    - develop
    - /^exercise-.*$/
    - /^feature\/.*$/
    - heroku/development
rvm:
  - 2.1.0
services:
  - mongodb
before_script:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES="YES"
  - bash scripts/before_script.bash
script:
  - export MONGODB_TEST_URL=mongo://localhost:27017/graph-visualizer-test MONGODB_URL=mongo://localhost:27017/graph-visualizer bash scripts/test.bash
after_script:
  - bash scripts/after_script.bash
env:
  global:
    - secure: "E7jPQ/LyZFl8l3/Zg3CPCrMM6WcAUFE7mfOObP36xLfTmkZWMA+QOFjxZsvgcHNEbaJdlsCRqN9vsSkobbt07G4YGbXOHojI/O8XA9oCfaGsKfiMt08l/kOsuJyQRe/fsn4MmfpxnQbPLs4zMtZxpqI6KR+fvYx3WIpvkl5mMyo="
gemfile:
  - Gemfile
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/57a11cd318bee6bc085f
    on_success: always
    on_failure: always
    on_start: always
deploy:
  provider: heroku
  api_key:
    secure: "h4UaaDKAkZrI4B3zoBB/oBiHGlMHsi7EKv74QpCJku/yvULdKFtHnjY13P6C3giIPGfMNLx58eZkkmiOM0wzfSIVRujXq4JyxqYa0x0MhByFjt/cLBUOKgSRcOZK8jH9BRhDG8Tkn6vD8nqQzvZoF8c7b1X3pEZNiSv+9DYaesk="
  app:
    heroku/development: graph-visualizer-xkb

